#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - tar
  - oracle-cloud-agent
runcmd:
  - systemctl enable oracle-cloud-agent
  - systemctl start oracle-cloud-agent
  - cd /home/ubuntu
  - curl -L "https://update.code.visualstudio.com/latest/cli-linux-arm64/stable" -o vscode_cli.tar.gz
  - tar -xf vscode_cli.tar.gz
  - chown -R ubuntu:ubuntu /home/ubuntu