#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - tar

write_files:
  - path: /home/ubuntu/setup-tunnel.sh
    permissions: '0755'
    owner: ubuntu:ubuntu
    content: |
      #!/bin/bash
      set -e

      export GITHUB_TOKEN="${github_token}"
      export INSTANCE_NAME="${instance_name}"

      cd /home/ubuntu

      # Download and extract VS Code CLI for Linux ARM64
      curl -L "https://code.visualstudio.com/sha/download?build=stable&os=cli-linux-arm64" --output vscode_cli.tar.gz
      tar -xf vscode_cli.tar.gz
      rm vscode_cli.tar.gz

      # Run the tunnel
      ./code tunnel --accept-server-license-terms --token "$GITHUB_TOKEN" --name "$INSTANCE_NAME"

runcmd:
  - [ su, - ubuntu, -c, "/home/ubuntu/setup-tunnel.sh" ]